# Project: StarkCombo
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"E:/programy/dewvcppwin8/MinGW64/lib32" -L"E:/programy/dewvcppwin8/MinGW64/x86_64-w64-mingw32/lib32" -L"E:/programy/gccSFML/lib" -m32 -g3
INCS     = -I"E:/programy/dewvcppwin8/MinGW64/include" -I"E:/programy/dewvcppwin8/MinGW64/x86_64-w64-mingw32/include" -I"E:/programy/dewvcppwin8/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/programy/dewvcppwin8/MinGW64/include" -I"E:/programy/dewvcppwin8/MinGW64/x86_64-w64-mingw32/include" -I"E:/programy/dewvcppwin8/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/programy/dewvcppwin8/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"E:/programy/gccSFML/include"
BIN      = StarkCombo.exe
CXXFLAGS = $(CXXINCS) -march=native -O3 -m32 -std=c++11 -g3
CFLAGS   = $(INCS) -march=native -O3 -m32 -std=c++11 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
